-- Persistent, per-user rolling quotas for the Gemini-backed AI Coach.
-- The table lives outside the exposed public schema and is only accessible
-- through the security-definer function below.

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists private.coach_api_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  bucket text not null check (bucket in ('chat', 'feedback')),
  requested_at timestamptz not null default now()
);

create index if not exists coach_api_usage_window_idx
  on private.coach_api_usage (user_id, bucket, requested_at desc);

alter table private.coach_api_usage enable row level security;
revoke all on private.coach_api_usage from public, anon, authenticated;

create or replace function public.consume_coach_quota(p_bucket text)
returns table (allowed boolean, remaining integer, retry_after integer)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_limit integer;
  v_window interval;
  v_count integer;
  v_oldest timestamptz;
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;

  case p_bucket
    when 'chat' then
      v_limit := 30;
      v_window := interval '10 minutes';
    when 'feedback' then
      v_limit := 10;
      v_window := interval '1 hour';
    else
      raise exception 'Unknown quota bucket' using errcode = '22023';
  end case;

  -- Serialize quota consumption for this user and bucket. This makes the
  -- count/insert sequence safe when multiple Edge requests arrive together.
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(v_user_id::text || ':' || p_bucket, 0)
  );

  delete from private.coach_api_usage
  where user_id = v_user_id
    and bucket = p_bucket
    and requested_at <= pg_catalog.now() - v_window;

  select count(*)::integer, min(requested_at)
    into v_count, v_oldest
  from private.coach_api_usage
  where user_id = v_user_id and bucket = p_bucket;

  if v_count >= v_limit then
    return query select
      false,
      0,
      greatest(
        1,
        ceil(extract(epoch from ((v_oldest + v_window) - pg_catalog.now())))::integer
      );
    return;
  end if;

  insert into private.coach_api_usage (user_id, bucket)
  values (v_user_id, p_bucket);

  return query select
    true,
    v_limit - v_count - 1,
    extract(epoch from v_window)::integer;
end;
$$;

revoke all on function public.consume_coach_quota(text) from public, anon;
grant execute on function public.consume_coach_quota(text) to authenticated;

comment on function public.consume_coach_quota(text) is
  'Atomically consumes the authenticated user AI Coach quota for chat or feedback.';
